import { type FormEvent, type ReactNode, useEffect, useMemo, useState } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { Link, Route, Switch, Router as WouterRouter, useLocation } from 'wouter';
import { Activity, AlertTriangle, Check, ChevronRight, CircleHelp, History as HistoryIcon, LayoutDashboard, LogOut, Menu, Moon, Play, RefreshCcw, Settings as SettingsIcon, Sun, Users, X, Zap } from 'lucide-react';
import { motion } from 'framer-motion';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';
import { ErrorBoundary } from '@/components/error-boundary';
import { api, clearSession, getStoredUser, getToken, setSession } from '@/api/client';
import type { CommunityState, ComparePlansResult, DispatchPlan, ForecastData, LadderResponse, RunwayForecast, SafeUser, ScenarioEventPayload, SignalState } from '@/types/navya';
import '@/index.css';

const queryClient = new QueryClient();
const navItems = [
  { href: '/', label: 'Control center', icon: LayoutDashboard },
  { href: '/forecast', label: 'Forecast', icon: Activity },
  { href: '/scenarios', label: 'Scenarios', icon: Zap },
  { href: '/community', label: 'Community', icon: Users },
  { href: '/history', label: 'History', icon: HistoryIcon },
  { href: '/settings', label: 'Settings', icon: SettingsIcon },
];

function useResource<T>(loader: () => Promise<T>, deps: unknown[] = [], interval?: number) {
  const [state, setState] = useState<{data?:T; loading:boolean; error?:string}>({ loading:true });
  const reload = () => { setState(s => ({ ...s, loading: !s.data, error: undefined })); loader().then(data => setState({ data, loading:false })).catch(error => setState(s => ({ ...s, loading:false, error:error instanceof Error ? error.message : 'Unable to reach NAVYA' }))); };
  useEffect(() => { reload(); const timer = interval ? window.setInterval(reload, interval) : undefined; return () => { if (timer) window.clearInterval(timer); }; }, deps);
  return { ...state, reload };
}

function Panel({ title, eyebrow, children, action }: { title:string; eyebrow?:string; children:ReactNode; action?:ReactNode }) {
  return <section className="hairline bg-[var(--panel)]">
    <div className="flex items-center justify-between border-b border-[var(--border)] px-4 py-3">
      <div><p className="mono text-[10px] uppercase tracking-[.16em] text-[var(--text-secondary)]">{eyebrow || 'NAVYA / OPERATIONS'}</p><h2 className="mt-1 text-[15px] font-semibold tracking-[-.01em]">{title}</h2></div>
      {action}
    </div>
    <div className="p-4">{children}</div>
  </section>;
}

function SignalBadge({ signal, compact = false }: { signal?:SignalState; compact?:boolean }) {
  const color = signal?.color || 'YELLOW';
  const text = signal?.message || 'Signal unavailable';
  return <div data-testid="status-signal" className={`inline-flex items-center gap-2 border px-3 py-2 ${color === 'RED' ? 'border-[var(--accent-alert)] text-[var(--accent-alert)]' : color === 'GREEN' ? 'border-[var(--accent-battery)] text-[var(--accent-battery)]' : 'border-[var(--accent-diesel)] text-[var(--accent-diesel)]'}`}>
    <span className={`signal-dot signal-${color.toLowerCase()}`} /><span className="mono text-[11px] font-semibold tracking-[.13em]">{color}</span>{!compact && <span className="hidden text-xs text-[var(--text-secondary)] sm:inline">{text}</span>}
  </div>;
}

function ThemeToggle() {
  const [dark, setDark] = useState(() => localStorage.getItem('navya_theme') === 'dark');
  useEffect(() => { document.documentElement.classList.toggle('dark', dark); localStorage.setItem('navya_theme', dark ? 'dark' : 'light'); }, [dark]);
  return <button data-testid="button-theme-toggle" aria-label="Toggle theme" onClick={() => setDark(v => !v)} className="hairline flex h-9 w-9 items-center justify-center bg-[var(--panel)] text-[var(--text-secondary)] hover:text-[var(--text-primary)]">{dark ? <Sun size={16} /> : <Moon size={16} />}</button>;
}

function Shell({ children, user, onLogout }: { children:ReactNode; user:SafeUser; onLogout:() => void }) {
  const [location] = useLocation(); const [mobileOpen, setMobileOpen] = useState(false);
  return <div className="min-h-[100dvh] bg-[var(--bg)]">
    <header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-[var(--border)] bg-[var(--bg)] px-4 md:px-7">
      <div className="flex items-center gap-5"><button className="md:hidden" data-testid="button-open-menu" onClick={() => setMobileOpen(true)}><Menu size={20} /></button><Link href="/" data-testid="link-wordmark" className="mono text-[18px] font-semibold tracking-[.22em]">NAVYA</Link><span className="hidden border-l border-[var(--border)] pl-5 text-xs text-[var(--text-secondary)] md:inline">microgrid operations / {new Date().toLocaleDateString('en-GB', { day:'2-digit', month:'short', year:'numeric' })}</span></div>
      <div className="flex items-center gap-3"><div className="hidden text-right sm:block"><div className="text-xs font-medium">{user.email}</div><div className="mono text-[10px] uppercase tracking-[.12em] text-[var(--text-secondary)]">{user.role || 'operator'}</div></div><ThemeToggle /><button data-testid="button-logout" aria-label="Sign out" onClick={onLogout} className="hairline flex h-9 w-9 items-center justify-center text-[var(--text-secondary)] hover:text-[var(--accent-alert)]"><LogOut size={15}/></button></div>
    </header>
    <div className="mx-auto flex max-w-[1640px]">
      <aside className="hidden w-56 shrink-0 border-r border-[var(--border)] px-3 py-5 md:block"><p className="mono mb-4 px-3 text-[9px] uppercase tracking-[.19em] text-[var(--text-secondary)]">Mission control</p>{navItems.map(item => { const Icon=item.icon; const active=location===item.href; return <Link key={item.href} href={item.href} data-testid={`link-nav-${item.label.toLowerCase().replaceAll(' ','-')}`} className={`flex items-center gap-3 border-l-2 px-3 py-2.5 text-sm ${active ? 'border-[var(--accent-battery)] bg-[var(--panel)] font-semibold' : 'border-transparent text-[var(--text-secondary)] hover:text-[var(--text-primary)]'}`}><Icon size={16}/>{item.label}</Link>; })}<div className="mt-8 border-t border-[var(--border)] pt-5 px-3"><div className="flex items-center gap-2 text-xs text-[var(--accent-battery)]"><span className="signal-dot signal-green"/><span>Autopilot active</span></div><p className="mt-2 text-[11px] leading-5 text-[var(--text-secondary)]">Continuous dispatch optimization is enabled.</p></div></aside>
      {mobileOpen && <div className="fixed inset-0 z-30 bg-[var(--text-primary)]/20 md:hidden" onClick={() => setMobileOpen(false)}><aside className="h-full w-72 border-r border-[var(--border)] bg-[var(--bg)] p-4" onClick={e => e.stopPropagation()}><div className="mb-8 flex items-center justify-between"><span className="mono font-semibold tracking-[.2em]">NAVYA</span><button onClick={() => setMobileOpen(false)}><X size={18}/></button></div>{navItems.map(item => <Link key={item.href} href={item.href} onClick={() => setMobileOpen(false)} className="flex items-center gap-3 border-b border-[var(--border)] py-4 text-sm"><item.icon size={16}/>{item.label}</Link>)}</aside></div>}
      <main className="min-w-0 flex-1 px-4 py-5 md:px-7 md:py-7">{children}</main>
    </div>
  </div>;
}

function PageIntro({ kicker, title, detail, action }: { kicker:string; title:string; detail:string; action?:ReactNode }) {
  return <div className="mb-6 flex flex-col justify-between gap-4 border-b border-[var(--border)] pb-5 md:flex-row md:items-end"><div><p className="mono text-[10px] uppercase tracking-[.18em] text-[var(--accent-battery)]">{kicker}</p><h1 className="mt-2 text-[clamp(25px,3vw,38px)] font-semibold tracking-[-.04em]">{title}</h1><p className="mt-2 max-w-2xl text-sm text-[var(--text-secondary)]">{detail}</p></div>{action}</div>;
}

function LoadingLines() { return <div className="space-y-3" data-testid="loading-state"><div className="h-3 w-2/3 animate-pulse bg-[var(--secondary)]"/><div className="h-3 w-1/2 animate-pulse bg-[var(--secondary)]"/><div className="h-16 animate-pulse bg-[var(--secondary)]"/></div>; }
function ErrorState({ error, retry }: { error?:string; retry:() => void }) { return <div data-testid="error-state" className="border border-[var(--accent-alert)]/40 bg-[var(--accent-alert)]/5 p-4"><div className="flex items-center gap-2 text-sm font-medium text-[var(--accent-alert)]"><AlertTriangle size={16}/>Connection interrupted</div><p className="mt-1 text-xs text-[var(--text-secondary)]">{error || 'NAVYA could not retrieve this live feed.'}</p><button data-testid="button-retry" onClick={retry} className="mt-3 flex items-center gap-2 text-xs font-semibold text-[var(--accent-alert)]"><RefreshCcw size={13}/> Retry</button></div>; }
function EmptyState({ label='Awaiting live backend data' }: {label?:string}) { return <div data-testid="empty-state" className="border border-dashed border-[var(--border)] p-7 text-center text-sm text-[var(--text-secondary)]"><Activity size={18} className="mx-auto mb-2 opacity-60"/>{label}</div>; }

function DigitalTwin({ state }: {state?:CommunityState}) {
  const generation = state?.generation; const demand=state ? state.demand.total_kw : 0;
  const sources = generation ? [{name:'SOLAR', value:generation.solar_kw, color:'var(--accent-solar)', x:110, y:62, icon:'sun'}, {name:'WIND', value:generation.wind_kw, color:'var(--accent-wind)', x:110, y:160, icon:'wind'}, {name:'BATTERY', value:generation.battery_discharge_kw, color:'var(--accent-battery)', x:110, y:258, icon:'battery'}, {name:'DIESEL', value:generation.diesel_kw, color:'var(--accent-diesel)', x:110, y:356, icon:'diesel'}] : [];
  return <div className="grid-paper relative min-h-[460px] overflow-hidden border border-[var(--border)] p-4 md:min-h-[530px]">
    <div className="absolute left-5 top-4 flex items-center gap-2"><span className="signal-dot signal-green"/><span className="mono text-[10px] uppercase tracking-[.14em] text-[var(--text-secondary)]">Live digital twin</span></div>
    {state && <div className="absolute right-5 top-4 text-right"><div className="mono text-sm font-semibold">{state.name}</div><div className="mono text-[10px] text-[var(--text-secondary)]">{new Date(state.timestamp).toLocaleTimeString()}</div></div>}
    {state ? <svg viewBox="0 0 900 440" className="mt-7 h-[420px] w-full md:h-[475px]" role="img" aria-label="Live microgrid single-line diagram">
      <line x1="335" y1="220" x2="590" y2="220" stroke="var(--border)" strokeWidth="5"/><line x1="335" y1="220" x2="590" y2="220" stroke="var(--accent-battery)" strokeWidth={Math.max(2, Math.min(10, (generation?.total_available_kw || 0)/(demand || 1)*5))} className="flow-line"/>
      {sources.map(source => <g key={source.name}><line x1={source.x+115} y1={source.y} x2="335" y2="220" stroke={source.color} strokeWidth={Math.max(2, Math.min(9, source.value / 12))} className="flow-line" /><rect x={source.x} y={source.y-25} width="115" height="50" fill="var(--panel)" stroke={source.color}/><text x={source.x+12} y={source.y-3} fill="var(--text-primary)" fontSize="11" fontWeight="600">{source.name}</text><text x={source.x+12} y={source.y+14} fill={source.color} fontSize="12" fontFamily="Geist Mono">{source.value.toFixed(1)} kW</text></g>)}
      <line x1="590" y1="220" x2="688" y2="220" stroke="var(--accent-battery)" strokeWidth="5" className="flow-line"/><rect x="590" y="170" width="98" height="100" fill="var(--panel)" stroke="var(--accent-battery)" strokeWidth="1.5"/><text x="603" y="197" fill="var(--text-primary)" fontSize="11" fontWeight="600">COMMUNITY</text><text x="603" y="223" fill="var(--accent-battery)" fontSize="16" fontFamily="Geist Mono" fontWeight="600">{demand.toFixed(1)}</text><text x="603" y="241" fill="var(--text-secondary)" fontSize="10">kW demand</text><text x="603" y="255" fill="var(--text-secondary)" fontSize="9">served bus</text>
      <text x="235" y="407" fill="var(--text-secondary)" fontSize="10" fontFamily="Geist Mono">AVAILABLE {generation?.total_available_kw.toFixed(1)} kW</text><text x="590" y="407" fill="var(--text-secondary)" fontSize="10" fontFamily="Geist Mono">STAGE {state.shortfall_stage}</text>
    </svg> : <div className="flex min-h-[430px] items-center justify-center"><EmptyState label="Digital twin waiting for /api/microgrid/state"/></div>}
  </div>;
}

function MetricsStrip({ state }: {state?:CommunityState}) {
  const items = state ? [{label:'Demand', value:`${state.demand.total_kw.toFixed(1)} kW`, accent:'var(--accent-wind)'},{label:'Battery SoC', value:`${state.battery.soc_pct.toFixed(1)}%`, accent:'var(--accent-battery)'},{label:'Diesel fuel', value:`${state.diesel.fuel_level_pct.toFixed(1)}%`, accent:'var(--accent-diesel)'},{label:'Weather', value:state.weather.condition || `${state.weather.temperature_c.toFixed(1)}°C`, accent:'var(--accent-solar)'}] : [];
  return <div className="grid grid-cols-2 border-x border-b border-[var(--border)] md:grid-cols-4">{items.length ? items.map(item => <div key={item.label} className="border-r border-[var(--border)] p-4 last:border-r-0"><div className="text-xs text-[var(--text-secondary)]">{item.label}</div><div data-testid={`value-${item.label.toLowerCase().replaceAll(' ','-')}`} className="mono mt-2 text-[19px] font-semibold" style={{color:item.accent}}>{item.value}</div></div>) : <div className="col-span-4 p-4"><EmptyState/></div>}</div>;
}

function OptimizerPanel({ plan, state, onOptimize }: {plan?:DispatchPlan; state?:CommunityState; onOptimize:()=>void}) {
  const [explanation, setExplanation] = useState<string>(); const [explaining, setExplaining] = useState(false);
  const explain = async () => { if (!plan) return; setExplaining(true); try { const result=await api.explain({ query:'Why is this dispatch plan recommended?', run_id:plan.plan_id }); setExplanation(result.explanation); } catch { setExplanation('Explanation is unavailable while the reasoning service is offline.'); } finally { setExplaining(false); } };
  return <Panel eyebrow="DECISION ENGINE" title="Optimizer decision" action={<button data-testid="button-optimize" onClick={onOptimize} className="flex items-center gap-2 border border-[var(--accent-battery)] px-3 py-2 text-xs font-semibold text-[var(--accent-battery)] hover:bg-[var(--accent-battery)]/10"><Play size={13}/> Run optimize</button>}>
    {plan ? <><div className="flex flex-wrap gap-x-8 gap-y-4 border-b border-[var(--border)] pb-4">{[['Cost',`$${plan.metrics.total_cost_usd.toFixed(2)}`],['CO₂',`${plan.metrics.total_co2_kg.toFixed(1)} kg`],['Renewable',`${plan.metrics.renewable_share_pct.toFixed(1)}%`],['Reliability',`${plan.metrics.reliability_score_pct.toFixed(1)}%`]].map(([label,value])=><div key={label}><p className="text-[11px] text-[var(--text-secondary)]">{label}</p><p className="mono mt-1 text-[16px] font-semibold">{value}</p></div>)}</div><div className="mt-4 flex items-start gap-3"><CircleHelp size={16} className="mt-0.5 shrink-0 text-[var(--accent-solar)]"/><div><p className="text-sm">{explanation || (state ? `Plan ${plan.plan_id} is ready. Ask NAVYA why this dispatch was selected.` : 'Dispatch explanation available after a live state update.')}</p><button data-testid="button-explain" onClick={explain} disabled={!plan || explaining} className="mt-3 text-xs font-semibold text-[var(--accent-battery)] disabled:opacity-50">{explaining ? 'Grounding explanation…' : explanation ? 'Refresh explanation' : 'Explain this decision'}</button></div></div></> : <EmptyState label="No optimizer run has been returned yet"/>}
  </Panel>;
}

function Ladder({ ladder, onRecalculate }: {ladder?:LadderResponse; onRecalculate:()=>void}) {
  const names=['Early warning','Preemptive pre-charge','Deferrable reschedule','Efficient diesel','Fair load shedding'];
  return <Panel eyebrow="RELIABILITY PROTOCOL" title="Shortfall response ladder" action={<button data-testid="button-recalculate-ladder" onClick={onRecalculate} className="text-xs text-[var(--text-secondary)] hover:text-[var(--text-primary)]"><RefreshCcw size={14}/></button>}>
    {ladder ? <><div className="space-y-2">{names.map((name,index) => <div key={name} className={`flex items-center gap-3 border-l-2 px-3 py-2 ${index === ladder.active_stage ? 'border-[var(--accent-alert)] bg-[var(--accent-alert)]/5' : index < ladder.active_stage ? 'border-[var(--accent-diesel)]' : 'border-[var(--border)]'}`}><span className="mono w-8 text-xs text-[var(--text-secondary)]">0{index}</span><span className={`text-xs ${index === ladder.active_stage ? 'font-semibold' : 'text-[var(--text-secondary)]'}`}>{name}</span>{index === ladder.active_stage && <span className="ml-auto mono text-[10px] uppercase text-[var(--accent-alert)]">active</span>}</div>)}</div><div className="mt-4 border-t border-[var(--border)] pt-3 text-xs text-[var(--text-secondary)]">{ladder.actions_taken.length ? ladder.actions_taken.join(' · ') : 'No intervention actions reported.'}</div></> : <EmptyState label="Ladder status unavailable"/>}
  </Panel>;
}

function Runway({ runway }: {runway?:RunwayForecast}) {
  const status = runway?.status; const color=status==='CRITICAL'?'var(--accent-alert)':status==='WARNING'?'var(--accent-diesel)':'var(--accent-battery)';
  return <Panel eyebrow="RESILIENCE" title="Fuel runway">{runway ? <><div className="flex items-end justify-between"><div><div className="mono text-4xl font-semibold" style={{color}}>{runway.days_of_diesel_remaining.toFixed(1)}</div><div className="mt-1 text-xs text-[var(--text-secondary)]">days of diesel remaining</div></div><span className="mono border px-2 py-1 text-[10px]" style={{borderColor:color,color}}>{status}</span></div><div className="mt-5 flex h-24 items-end gap-1 border-b border-[var(--border)]">{runway.daily_projections.slice(0,14).map((day) => <div key={day.day_offset} className="group relative flex-1" title={`${day.remaining_liters} L remaining`}><div className="w-full bg-[var(--accent-diesel)]/65" style={{height:`${Math.max(4, Math.min(100, day.remaining_liters / Math.max(1, runway.daily_projections[0]?.remaining_liters || 1) * 100))}%`}}/></div>)}</div><div className="mono mt-2 flex justify-between text-[10px] text-[var(--text-secondary)]"><span>today</span><span>projection / 14d</span></div></> : <EmptyState label="Runway projection unavailable"/>}</Panel>;
}

function OverrideConsole() {
  const [diesel,setDiesel]=useState(false); const [reserve,setReserve]=useState(''); const [reason,setReason]=useState(''); const [active,setActive]=useState(false); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState<string>();
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setNotice(undefined);try{const result=await api.override({force_diesel_on:diesel,min_battery_reserve_pct:reserve?Number(reserve):undefined,reason});setActive(true);setNotice(String(result.delta_text||result.message||'Manual override accepted by NAVYA.'));}catch(err){setNotice(err instanceof Error?err.message:'Override was not accepted.');}finally{setBusy(false);}};
  const clear=async()=>{setBusy(true);try{await api.clearOverride();setActive(false);setNotice('Autopilot restored.');}catch(err){setNotice(err instanceof Error?err.message:'Could not clear override.');}finally{setBusy(false);}};
  return <Panel eyebrow="OPERATOR CONTROL" title="Manual override" action={active?<span className="mono text-[10px] text-[var(--accent-alert)]">OVERRIDE ACTIVE</span>:undefined}><form onSubmit={submit} className="space-y-3"><label className="flex items-center gap-3 text-xs"><input data-testid="input-force-diesel" type="checkbox" checked={diesel} onChange={e=>setDiesel(e.target.checked)} className="accent-[var(--accent-diesel)]"/> Force diesel on</label><label className="block"><span className="text-[11px] text-[var(--text-secondary)]">Minimum battery reserve (%)</span><input data-testid="input-battery-reserve" type="number" min="0" max="100" value={reserve} onChange={e=>setReserve(e.target.value)} placeholder="Backend default" className="mt-1 w-full border border-[var(--border)] bg-[var(--bg)] px-2 py-2 text-xs outline-none focus:border-[var(--accent-diesel)]"/></label><label className="block"><span className="text-[11px] text-[var(--text-secondary)]">Reason</span><input data-testid="input-override-reason" required value={reason} onChange={e=>setReason(e.target.value)} placeholder="Operational reason" className="mt-1 w-full border border-[var(--border)] bg-[var(--bg)] px-2 py-2 text-xs outline-none focus:border-[var(--accent-diesel)]"/></label><div className="flex gap-2"><button data-testid="button-submit-override" disabled={busy} className="bg-[var(--accent-diesel)] px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">Submit override</button>{active&&<button type="button" data-testid="button-clear-override" disabled={busy} onClick={clear} className="border border-[var(--border)] px-3 py-2 text-xs">Clear</button>}</div></form>{notice&&<div data-testid="text-override-result" className="mt-3 border-l-2 border-[var(--accent-diesel)] pl-3 text-xs text-[var(--text-secondary)]">{notice}</div>}</Panel>;
}

function ControlCenter() {
  const state=useResource(api.state,[],5000); const ladder=useResource(api.ladder,[]); const runway=useResource(api.runway,[]);
  const [plan,setPlan]=useState<DispatchPlan>(); const [optimizing,setOptimizing]=useState(false);
  const optimize=async()=>{setOptimizing(true);try{setPlan(await api.optimize());}catch{}finally{setOptimizing(false);}};
  const recalc=async()=>{try{const result=await api.recalculateLadder(); ladder.reload(); return result;}catch{return undefined;}};
  return <><PageIntro kicker="LIVE / CONTROL CENTER" title="Control center" detail="A single operational view of the community microgrid. NAVYA is continuously watching supply, demand, and resilience." action={<div className="flex flex-wrap items-center gap-2"><SignalBadge signal={state.data?.signal}/><div className="flex items-center gap-2 border border-[var(--accent-battery)] px-3 py-2 text-xs text-[var(--accent-battery)]"><span className="signal-dot signal-green"/> AUTOPILOT ACTIVE</div></div>}/><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><div><DigitalTwin state={state.data}/><MetricsStrip state={state.data}/></div><div className="space-y-5"><OptimizerPanel plan={plan} state={state.data} onOptimize={optimize}/><Ladder ladder={ladder.data} onRecalculate={recalc}/><Runway runway={runway.data}/><OverrideConsole/></div></div>{(state.error || ladder.error || runway.error) && <div className="mt-5"><ErrorState error={state.error || ladder.error || runway.error} retry={() => {state.reload();ladder.reload();runway.reload();}}/></div>}{optimizing && <div className="fixed bottom-5 right-5 border border-[var(--accent-battery)] bg-[var(--panel)] px-4 py-3 text-xs text-[var(--accent-battery)]">Optimizer is evaluating dispatch…</div>}</>;
}

function Forecast() {
  const [horizon,setHorizon]=useState<0|24|72>(24); const forecast=useResource<ForecastData>(()=>horizon===0?Promise.resolve({horizon_hours:0,hourly_forecast:[]}):api.forecast(horizon),[horizon]); const now=useResource(api.state,[]);
  const current=now.data; const items=forecast.data?.hourly_forecast;
  return <><PageIntro kicker="LOOK AHEAD / WEATHER + LOAD" title="Forecast" detail="Read the next operating window before it becomes an incident." action={<div className="flex border border-[var(--border)]">{[0,24,72].map(value=><button key={value} data-testid={`button-horizon-${value||'now'}`} onClick={()=>setHorizon(value as 0|24|72)} className={`px-4 py-2 text-xs ${horizon===value?'bg-[var(--text-primary)] text-[var(--bg)]':'text-[var(--text-secondary)]'}`}>{value===0?'NOW':`${value}H`}</button>)}</div>}/><Panel eyebrow={`FORECAST / ${horizon===0?'NOW':`${horizon} HOURS`}`} title="Supply and demand timeline">{horizon===0 ? current ? <div className="grid gap-4 sm:grid-cols-3"><div><div className="text-xs text-[var(--text-secondary)]">Live demand</div><div className="mono mt-2 text-3xl">{current.demand.total_kw.toFixed(1)} kW</div></div><div><div className="text-xs text-[var(--text-secondary)]">Available generation</div><div className="mono mt-2 text-3xl text-[var(--accent-battery)]">{current.generation.total_available_kw.toFixed(1)} kW</div></div><div><div className="text-xs text-[var(--text-secondary)]">Wind / solar</div><div className="mono mt-2 text-3xl text-[var(--accent-wind)]">{current.generation.wind_kw.toFixed(1)} / {current.generation.solar_kw.toFixed(1)} kW</div></div></div> : now.error?<ErrorState error={now.error} retry={now.reload}/>:<LoadingLines/> : forecast.loading && !forecast.data ? <LoadingLines/> : forecast.error && !forecast.data ? <ErrorState error={forecast.error} retry={forecast.reload}/> : items?.length ? <div className="overflow-x-auto"><div className="min-w-[720px]"><div className="mb-3 grid grid-cols-[100px_1fr] items-center text-[10px] uppercase tracking-wider text-[var(--text-secondary)]"><span>Time</span><span>Demand / renewable output</span></div>{items.map(item=><div key={item.time} className="grid grid-cols-[100px_1fr] items-center border-t border-[var(--border)] py-3"><div className="mono text-xs text-[var(--text-secondary)]">{new Date(item.time).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</div><div className="relative h-8"><div className="absolute left-0 top-1/2 h-px w-full bg-[var(--border)]"/><div className="absolute left-0 top-[7px] h-2 bg-[var(--accent-wind)]" style={{width:`${Math.min(100, item.total_demand_kw)}%`}}/><div className="absolute left-0 top-[20px] h-2 bg-[var(--accent-solar)]" style={{width:`${Math.min(100, item.predicted_solar_kw)}%`}}/><span className="mono absolute right-0 -top-1 text-[10px]">{item.total_demand_kw.toFixed(1)} kW</span></div></div>)}</div></div> : <EmptyState label="Forecast timeline is waiting for /api/forecast"/>}</Panel></>;
}

const scenarioButtons: {type:ScenarioEventPayload['scenario_type']; label:string; detail:string}[]=[{type:'CLOUD_COVER',label:'Cloud cover',detail:'Solar irradiance falls rapidly'},{type:'WIND_DROP',label:'Wind drop',detail:'Wind generation becomes unavailable'},{type:'BATTERY_FAULT',label:'Battery fault',detail:'Storage is removed from dispatch'},{type:'DEMAND_SURGE',label:'Demand surge',detail:'Community load rises sharply'},{type:'DIESEL_PRICE_SPIKE',label:'Diesel price spike',detail:'Fuel cost changes planning priority'}];
function PlanCompare({ result }: {result?:ComparePlansResult}) {
  if (!result) return <EmptyState label="Run compare plans to receive backend scenarios"/>;
  const rows=[['Cost','cost_usd','USD'],['CO₂','co2_kg','kg'],['Diesel','diesel_liters','L'],['Renewable','renewable_share_pct','%'],['Reliability','reliability_pct','%']] as const;
  return <div className="grid gap-3 md:grid-cols-3">{(['ai_optimal','diesel_first','renewable_first'] as const).map(key=><div key={key} className={`border p-4 ${key==='ai_optimal'?'border-[var(--accent-battery)]':'border-[var(--border)]'}`}><div className="flex items-center justify-between"><span className="mono text-[10px] uppercase tracking-wider">{key.replaceAll('_',' ')}</span>{key==='ai_optimal'&&<Check size={15} className="text-[var(--accent-battery)]"/>}</div><div className="mt-4 space-y-3">{rows.map(([label,field,unit])=><div key={field} className="flex justify-between text-xs"><span className="text-[var(--text-secondary)]">{label}</span><span className="mono">{result[key][field].toFixed(1)} {unit}</span></div>)}</div></div>)}</div>;
}
function Scenarios() {
  const [busy,setBusy]=useState<string>(); const [message,setMessage]=useState<string>(); const [compare,setCompare]=useState<ComparePlansResult>();
  const run=async(type:ScenarioEventPayload['scenario_type'],name:string)=>{setBusy(type);setMessage(undefined);try{const plan=await api.scenario({scenario_type:type,name,parameters:{}});setMessage(`Grid stabilized. NAVYA returned dispatch ${plan.plan_id}.`);}catch(e){setMessage(e instanceof Error?e.message:'Scenario unavailable.');}finally{setBusy(undefined);}};
  const comparePlans=async()=>{try{setCompare(await api.compare());}catch{setMessage('Compare plans is unavailable while the backend is offline.');}};
  return <><PageIntro kicker="WHAT-IF / CONSEQUENCE" title="Scenario lab" detail="Inject a disturbance into the live model. Each result is a backend re-optimization, not a client-side projection."/><div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Panel eyebrow="SCENARIO INJECTION" title="Choose a trigger"><div className="grid gap-2 sm:grid-cols-2">{scenarioButtons.map(button=><button key={button.type} data-testid={`button-scenario-${button.type.toLowerCase()}`} disabled={Boolean(busy)} onClick={()=>run(button.type,button.label)} className="flex items-center justify-between border border-[var(--border)] p-4 text-left hover:border-[var(--accent-solar)] disabled:opacity-50"><span><span className="block text-sm font-medium">{button.label}</span><span className="mt-1 block text-xs text-[var(--text-secondary)]">{button.detail}</span></span>{busy===button.type?<RefreshCcw size={16} className="animate-spin text-[var(--accent-solar)]"/>:<ChevronRight size={16} className="text-[var(--text-secondary)]"/>}</button>)}</div>{message&&<motion.div initial={{opacity:0, y:4}} animate={{opacity:1, y:0}} transition={{duration:.2, ease:'easeOut'}} data-testid="text-scenario-result" className="mt-4 border-l-2 border-[var(--accent-battery)] bg-[var(--accent-battery)]/5 p-3 text-sm">{message}</motion.div>}</Panel><Panel eyebrow="STRATEGY REVIEW" title="Compare plans" action={<button data-testid="button-compare-plans" onClick={comparePlans} className="border border-[var(--border)] px-3 py-2 text-xs hover:border-[var(--accent-battery)]">Compare</button>}><PlanCompare result={compare}/></Panel></div></>;
}

function Community() {
  const state=useResource(api.state); const community=useResource(api.community); const assets=useResource(api.assets);
  const breakdown=state.data?.demand.tier_breakdown;
  const tiers=breakdown ? [{tier:'01',name:'Critical',detail:'Health clinic / emergency systems',kw:breakdown.tier1_critical_kw,color:'var(--accent-alert)'},{tier:'02',name:'Important',detail:'Water pumping / sanitation',kw:breakdown.tier2_important_kw,color:'var(--accent-diesel)'},{tier:'03',name:'Standard',detail:'Schools / homes / community center',kw:breakdown.tier3_standard_kw,color:'var(--accent-wind)'},{tier:'04',name:'Flexible',detail:'EV charging / industry',kw:breakdown.tier4_flexible_kw,color:'var(--accent-solar)'}] : [];
  return <><PageIntro kicker="COMMUNITY / LOAD TIERS" title="Community" detail="A visible contract between energy availability and the loads NAVYA protects."/><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Panel eyebrow="DEMAND ALLOCATION" title="Load tiers"><div className="space-y-2">{tiers.length?tiers.map(tier=><div key={tier.tier} className="grid grid-cols-[38px_1fr_auto] items-center gap-3 border-b border-[var(--border)] py-4 last:border-0"><span className="mono text-xs text-[var(--text-secondary)]">{tier.tier}</span><div><div className="text-sm font-semibold">{tier.name}</div><div className="text-xs text-[var(--text-secondary)]">{tier.detail}</div></div><div className="mono text-sm" style={{color:tier.color}}>{tier.kw.toFixed(1)} kW</div></div>):<EmptyState label="Load tiers waiting for live state"/>}</div></Panel><div className="space-y-5"><Panel eyebrow="COMMUNITY PROFILE" title="Operational context">{community.data ? <pre data-testid="community-profile" className="overflow-auto whitespace-pre-wrap text-xs text-[var(--text-secondary)]">{JSON.stringify(community.data,null,2)}</pre> : community.error?<ErrorState error={community.error} retry={community.reload}/>:<LoadingLines/>}</Panel><Panel eyebrow="CONNECTED ASSETS" title="Community assets">{assets.data?.length ? <div className="space-y-2">{assets.data.map((asset,index)=><div key={index} className="border-b border-[var(--border)] py-2 text-xs">{JSON.stringify(asset)}</div>)}</div>:<EmptyState label="No asset inventory returned"/>}</Panel></div></div></>;
}

function History() {
  const optimize=useResource(api.optimizeHistory); const scenarios=useResource(api.scenarioHistory); const overrides=useResource(api.overrideHistory);
  const events=useMemo(()=>([...(optimize.data||[]).map(item=>({...item,_kind:'optimization'})),...(scenarios.data||[]).map(item=>({...item,_kind:'scenario'})),...(overrides.data||[]).map(item=>({...item,_kind:'override'}))] as Array<Record<string, unknown> & {_kind:string}>).sort((a,b)=>String(b.timestamp||b.created_at||'').localeCompare(String(a.timestamp||a.created_at||''))),[optimize.data,scenarios.data,overrides.data]);
  return <><PageIntro kicker="AUDIT / DECISIONS" title="History" detail="A merged record of optimizer runs, scenario injections, and operator overrides."/><Panel eyebrow="EVENT FEED" title={`${events.length} recorded events`} action={<button data-testid="button-refresh-history" onClick={()=>{optimize.reload();scenarios.reload();overrides.reload();}}><RefreshCcw size={15}/></button>}>{events.length?<div className="divide-y divide-[var(--border)]">{events.map((event,index)=><div key={index} data-testid={`row-history-${index}`} className="grid gap-2 py-4 md:grid-cols-[120px_120px_1fr]"><span className="mono text-[10px] text-[var(--text-secondary)]">{String(event.timestamp||event.created_at||'—')}</span><span className="mono text-[10px] uppercase text-[var(--accent-battery)]">{event._kind}</span><span className="text-xs text-[var(--text-secondary)]">{JSON.stringify(event)}</span></div>)}</div>:<EmptyState label="No history returned by the backend"/>}</Panel></>;
}

function Settings() {
  const resource=useResource(api.parameters); const [form,setForm]=useState<Record<string,string>>({}); const [saved,setSaved]=useState(false); const [saving,setSaving]=useState(false);
  useEffect(()=>{if(resource.data)setForm(Object.fromEntries(Object.entries(resource.data).map(([key,value])=>[key,String(value)])));},[resource.data]);
  const save=async(e:FormEvent)=>{e.preventDefault();setSaving(true);try{const payload=Object.fromEntries(Object.entries(form).map(([key,value])=>[key,value.trim()!==''&&!Number.isNaN(Number(value))?Number(value):value]));await api.saveParameters(payload);setSaved(true);setTimeout(()=>setSaved(false),2400);}catch{}finally{setSaving(false);}};
  return <><PageIntro kicker="SYSTEM / PARAMETERS" title="Settings" detail="Small, deliberate changes to the physical model. Values are written to the NAVYA backend."/><div className="max-w-2xl"><Panel eyebrow="MICROGRID PARAMETERS" title="Operating model">{resource.error&&!resource.data?<ErrorState error={resource.error} retry={resource.reload}/>:resource.loading&&!resource.data?<LoadingLines/>:<form onSubmit={save} className="space-y-4">{Object.keys(form).length?Object.entries(form).map(([key,value])=><label key={key} className="block"><span className="mono text-[10px] uppercase tracking-wider text-[var(--text-secondary)]">{key.replaceAll('_',' ')}</span><input data-testid={`input-parameter-${key}`} value={value} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-1 block w-full border border-[var(--border)] bg-[var(--bg)] px-3 py-2 text-sm outline-none focus:border-[var(--accent-battery)]"/></label>):<EmptyState label="Parameters endpoint returned no editable fields"/>}<div className="flex items-center gap-4 pt-2"><button data-testid="button-save-settings" disabled={saving||!Object.keys(form).length} className="bg-[var(--accent-battery)] px-4 py-2 text-xs font-semibold text-white disabled:opacity-50">{saving?'Saving…':'Save parameters'}</button>{saved&&<span className="text-xs text-[var(--accent-battery)]">Parameters saved.</span>}</div></form>}</Panel></div></>;
}

function Login({ onLogin }: {onLogin:(user:SafeUser)=>void}) {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [register,setRegister]=useState(false); const [error,setError]=useState<string>(); const [busy,setBusy]=useState(false);
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError(undefined);try{const result=register?await api.register({email,password}):await api.login({email,password});setSession(result.token,result.user);onLogin(result.user);}catch(err){setError(err instanceof Error?err.message:'Unable to authenticate');}finally{setBusy(false);}};
  return <div className="grid min-h-[100dvh] bg-[var(--bg)] md:grid-cols-[1.1fr_.9fr]"><div className="grid-paper hidden border-r border-[var(--border)] p-10 md:flex md:flex-col md:justify-between"><div className="mono text-lg font-semibold tracking-[.2em]">NAVYA</div><div><p className="mono text-[10px] uppercase tracking-[.18em] text-[var(--accent-battery)]">Autonomous energy management</p><h1 className="mt-4 max-w-lg text-5xl font-semibold leading-[.95] tracking-[-.06em]">Run the grid.<br/>Keep the promise.</h1><p className="mt-6 max-w-sm text-sm leading-6 text-[var(--text-secondary)]">Mission control for off-grid communities — precise dispatch, clear consequences, resilient decisions.</p></div><div className="mono text-[10px] uppercase tracking-[.15em] text-[var(--text-secondary)]">Secure operator access / v1</div></div><div className="flex items-center justify-center p-6"><form onSubmit={submit} className="w-full max-w-sm"><div className="mb-10 md:hidden"><div className="mono text-lg font-semibold tracking-[.2em]">NAVYA</div></div><p className="mono text-[10px] uppercase tracking-[.18em] text-[var(--accent-battery)]">Operator access</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em]">{register?'Create operator account':'Welcome back'}</h2><p className="mt-2 text-sm text-[var(--text-secondary)]">{register?'Register access to this microgrid.':'Sign in to the live control center.'}</p><div className="mt-8 space-y-4"><label className="block"><span className="text-xs">Email</span><input data-testid="input-email" required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full border border-[var(--border)] bg-[var(--panel)] px-3 py-3 outline-none focus:border-[var(--accent-battery)]"/></label><label className="block"><span className="text-xs">Password</span><input data-testid="input-password" required type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full border border-[var(--border)] bg-[var(--panel)] px-3 py-3 outline-none focus:border-[var(--accent-battery)]"/></label></div>{error&&<p data-testid="text-login-error" className="mt-4 text-xs text-[var(--accent-alert)]">{error}</p>}<button data-testid="button-login" disabled={busy} className="mt-6 w-full bg-[var(--accent-battery)] py-3 text-sm font-semibold text-white disabled:opacity-50">{busy?'Connecting…':register?'Create account':'Enter control center'}</button><button type="button" data-testid="button-toggle-register" onClick={()=>setRegister(v=>!v)} className="mt-4 w-full text-xs text-[var(--text-secondary)] hover:text-[var(--text-primary)]">{register?'Already have access? Sign in':'Need access? Register'}</button></form></div></div>;
}

function CommunityDisplay() {
  const cachedKey='navya_signal_cache'; const [cached,setCached]=useState<SignalState|undefined>(()=>{try{return JSON.parse(localStorage.getItem(cachedKey)||'null') as SignalState|undefined}catch{return undefined}}); const [offline,setOffline]=useState(false);
  useEffect(()=>{const poll=()=>api.signal().then(signal=>{setCached(signal);setOffline(false);localStorage.setItem(cachedKey,JSON.stringify(signal));}).catch(()=>setOffline(true));poll();const timer=window.setInterval(poll,10000);return()=>window.clearInterval(timer);},[]);
  const color=cached?.color || 'YELLOW'; const colorValue=color==='GREEN'?'var(--accent-battery)':color==='RED'?'var(--accent-alert)':'var(--accent-diesel)';
  return <main className="flex min-h-[100dvh] flex-col justify-between bg-[var(--bg)] p-6 md:p-12"><div className="flex items-center justify-between"><div className="mono text-xl font-semibold tracking-[.2em]">NAVYA</div><div className="mono text-[10px] uppercase tracking-[.16em] text-[var(--text-secondary)]">{offline?'cached signal':'signal relay'}</div></div><div className="mx-auto w-full max-w-4xl py-20"><div className="flex items-center gap-3"><span className={`signal-dot signal-${color.toLowerCase()}`}/><span className="mono text-xs uppercase tracking-[.2em]" style={{color:colorValue}}>{color}</span></div><h1 data-testid="kiosk-signal-message" className="mt-7 max-w-3xl text-[clamp(40px,8vw,100px)] font-semibold leading-[.9] tracking-[-.07em]" style={{color:colorValue}}>{cached?.message || 'Signal unavailable'}</h1><div className="mt-10 flex items-center gap-4 border-t border-[var(--border)] pt-5 text-xs text-[var(--text-secondary)]"><span>Community energy signal</span>{cached?.updated_at&&<span className="mono">{new Date(cached.updated_at).toLocaleTimeString()}</span>}{offline&&<span className="border border-[var(--accent-diesel)] px-2 py-1 text-[var(--accent-diesel)]">LAST GOOD READING</span>}</div></div><div className="mono flex justify-between text-[10px] uppercase tracking-[.15em] text-[var(--text-secondary)]"><span>Public display</span><span>Refreshes every 10s</span></div></main>;
}

function NotFound() { return <div className="flex min-h-[80vh] items-center justify-center"><div className="text-center"><p className="mono text-xs text-[var(--accent-alert)]">404 / ROUTE NOT FOUND</p><h1 className="mt-3 text-3xl font-semibold">This console page does not exist.</h1><Link href="/" className="mt-5 inline-block text-sm text-[var(--accent-battery)]">Return to control center</Link></div></div>; }

function AuthenticatedRouter({ user, onLogout }: {user:SafeUser;onLogout:()=>void}) {
  return <Shell user={user} onLogout={onLogout}><Switch><Route path="/" component={ControlCenter}/><Route path="/forecast" component={Forecast}/><Route path="/scenarios" component={Scenarios}/><Route path="/community" component={Community}/><Route path="/history" component={History}/><Route path="/settings" component={Settings}/><Route component={NotFound}/></Switch></Shell>;
}

function App() {
  const [user,setUser]=useState<SafeUser|null>(()=>getToken()?getStoredUser():null);
  const [location,setLocation]=useLocation();
  useEffect(()=>{document.title='NAVYA — Microgrid Operations'; if(getToken()&&!user)api.me().then(setUser).catch(()=>{clearSession();setLocation('/login');});},[]);
  useEffect(()=>{if(user && location==='/login') setLocation('/');},[user,location,setLocation]);
  if (location==='/community-display') return <CommunityDisplay/>;
  if (!user) return <Login onLogin={value=>{setUser(value);setLocation('/');}}/>;
  return <AuthenticatedRouter user={user} onLogout={()=>{clearSession();setUser(null);setLocation('/login');}}/>;
}

export default function RootApp() {
  return <QueryClientProvider client={queryClient}><TooltipProvider><WouterRouter><ErrorBoundary><App/></ErrorBoundary></WouterRouter><Toaster/></TooltipProvider></QueryClientProvider>;
}
